import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "swiper/css";
import "rc-slider/assets/index.css";
import "../css/output.css";
import { Box, Container } from "@mui/material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>{"vakratunda sk paithani"}</title>

        <meta
          name="google-site-verification"
          content="uekPvgvSmjuATzDfa7Gwm3DVHPDk0obila4r-7tj-KY"
        />
        <meta
          name="keywords"
          content="vakratunda-sk-paithani,paithanis,sarees,vakratunda-paithani,sk-paithani"
        ></meta>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <meta name="theme-color" content="#111111" />
        <meta name="format-detection" content="telephone=no" />
        <meta
          name="description"
          content="Looking for Paithani Sarees online? vakratunda-sk-paithani.com offers 100% original Paithani Silk Sarees, Yeola Paithani Sarees, 9 Yards Sarees, Bridal Sarees &amp; more!"
        />
        <meta property="og:site_name" content="vakratunda-sk-paithani" />
        <meta property="og:title" content={"vakratunda sk paithani"} />
        <meta
          property="og:url"
          content="https://vakratunda-sk-paithani.vercel.app/"
        />
        <meta property="og:type" content="website" />
        <meta
          property="og:description"
          content="Looking for Paithani Sarees online? vakratunda-sk-paithani.com offers 100% original Paithani Silk Sarees, Yeola Paithani Sarees, 9 Yards Sarees, Bridal Sarees &amp; more!"
        />
        <meta
          property="og:image"
          content="http://cdn.shopify.com/s/files/1/0308/8495/4252/files/FB_1_1200x630.jpg?v=1613691615"
        />
        <meta
          property="og:image:secure_url"
          content="https://cdn.shopify.com/s/files/1/0308/8495/4252/files/FB_1_1200x630.jpg?v=1613691615"
        />
        <meta name="twitter:site" content="@vakratunda-sk-paithani" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={"vakratunda sk paithani"} />
        <meta
          name="twitter:description"
          content="Looking for Paithani Sarees online? vakratunda-sk-paithani.com offers 100% original Paithani Silk Sarees, Yeola Paithani Sarees, 9 Yards Sarees, Bridal Sarees &amp; more!"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container-feather">
          <div className="feather1">
            <div className="base-feather"></div>
            <div className="line-feather-1"></div>
            <div className="line-feather-2"></div>
            <div className="line-feather-3"></div>
            <div className="middle-feather-line"></div>
            <div className="middle-circle"></div>
            <div className="blue-circle"></div>
          </div>
          <div className="feather2">
            <div className="base-feather"></div>
            <div className="line-feather-1"></div>
            <div className="line-feather-2"></div>
            <div className="line-feather-3"></div>
            <div className="middle-feather-line"></div>
            <div className="middle-circle"></div>
            <div className="blue-circle"></div>
          </div>
          <div className="feather3">
            <div className="base-feather"></div>
            <div className="line-feather-1"></div>
            <div className="line-feather-2"></div>
            <div className="line-feather-3"></div>
            <div className="middle-feather-line"></div>
            <div className="middle-circle"></div>
            <div className="blue-circle"></div>
          </div>
          <div className="feather4">
            <div className="base-feather"></div>
            <div className="line-feather-1"></div>
            <div className="line-feather-2"></div>
            <div className="line-feather-3"></div>
            <div className="middle-feather-line"></div>
            <div className="middle-circle"></div>
            <div className="blue-circle"></div>
          </div>
          <div className="feather5">
            <div className="base-feather"></div>
            <div className="line-feather-1"></div>
            <div className="line-feather-2"></div>
            <div className="line-feather-3"></div>
            <div className="middle-feather-line"></div>
            <div className="middle-circle"></div>
            <div className="blue-circle"></div>
          </div>
        </div>
        <Container>
          <Header />
          <Box sx={{ mt: 11 }}> {children}</Box>

          <Footer />
        </Container>
      </body>
    </html>
  );
}
